### ISSUE TITLE
The example in the documentation doesn't work

### ISSUE THREAD

**Issue by mohamedrajhi** [decentralized-identity/did-jwt#119]
Hello , i tried to run this example but the variable jwt remain empty , i think there is a bug in your code , the response is always empty
```
const didJWT = require('did-jwt')
const signer = didJWT.SimpleSigner('278a5de700e29faae8e40e366ec5012b5ec63d36ec77e8a2417154cc1d25383f');

let jwt = '';
didJWT.createJWT({aud: 'did:ethr:0xf3beac30c498d9e26865f34fcaa57dbb935b0d74', exp: 1957463421, name: 'uPort Developer'},
                 {alg: 'ES256K-R', issuer: 'did:ethr:0xf3beac30c498d9e26865f34fcaa57dbb935b0d74', signer}).then( response =>
                 { jwt = response });

console.log(jwt);
```

**Comment by aletell** [comment]
take a look at promises, if you use an async function you could use it as in the other programming languages

**Comment by mirceanis** [comment]
Thanks for spotting this.
There's a typo and the `console.log` should be inside the `then` block, right after the `jwt = response` statement. 

Feel free to open a PR to correct this mistake if this fixes your problem.

**Comment by mohamedrajhi** [comment]
> Thanks for spotting this.
> There's a typo and the `console.log` should be inside the `then` block, right after the `jwt = response` statement.
> 
> Feel free to open a PR to correct this mistake if this fixes your problem.

thanks @mirceanis
