### ISSUE TITLE
Correct way to handle reject in verifyJWT

### ISSUE THREAD

**Issue by nlaitanatix** [decentralized-identity/did-jwt#133]
As title says, what is the correct way to handle a rejection in verifyJWT method? 

What I try to do is:
```
verifyJWT(jwt, options)
  .then(...)
  .catch(error => console.log(error))
```

and 

```
try {
   const result = await verifyJWT(jwt, options);
} catch(e) {
   throw e;
}
```
but the node console always says
```
UnhandledPromiseRejectionWarning: Unhandled promise rejection. 
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```
And the request stays in pending status until socket hung ups

**Comment by mirceanis** [comment]
You are doing it right and it should not throw that error.
Can you post a tiny project that exhibits this behavior?

**Comment by nlaitanatix** [comment]
> You are doing it right and it should not throw that error.
> Can you post a tiny project that exhibits this behavior?

Thank you for the response! I cant put here the whole code flow but what I can do is put the functions that call it:

```
const verifyToken = async (jwt, isUser = false) => {
	const options = {
		resolver,
		audience: serverDid
	};
	try {
		return await verifyJWT(jwt, options);
	} catch (error) {
                // errorMessages is an object with personalized messages
		const message = errorMessages[error.name] || INVALID_CODE(isUser);
		throw message;
	}
};
```
The above function is in turn enclosed in a general trycatch within the path from which it is invoked

What I tried and with which I got this error, was to edit the token manually by adding or modifying some letter. The console shows the error (invalid length for example), but does not go the way of rejection

**Comment by mirceanis** [comment]
Is this still an issue?

It seems that this is a misunderstanding of `async`

In your code from before, `verifyToken` is going to return a `Promise`.
To get away from the `unhandled promise rejection` error, you need to `catch()`:
```ts
verifyToken(token)
  .then((result) => { console.log('token was verified:', token) })
  .catch((error) => { console.log('bad token', error) })
```

I'm closing this. Please reopen if this is still an issue, but please also link to a project that shows the failure.. not just a snippet of code.
