### ISSUE TITLE
JWT verification: skewed times comparison

### ISSUE THREAD

**Issue by javiesses** [decentralized-identity/did-jwt#136]
Hi team!

I'm trying to verify some JWTs and I realised that `nbf`, `iat` and `exp` times are being compared to a skewed time (5 minutes) instead of the current one, is there any reason for that?

https://github.com/decentralized-identity/did-jwt/blob/c91d38cdd06635b418250048e329c509eab1e6d6/src/JWT.ts#L88
https://github.com/decentralized-identity/did-jwt/blob/7c6b10507a4c35c0bef0a82874507786b1dc8f56/src/JWT.ts#L252-L262

Thanks in advance!

**Comment by mirceanis** [comment]
Hi, yes.
The most relevant reason is that usually issuance and verification happen on different machines, whose clocks don't perfectly align.
If you issue a JWT with identical `nbf` and `exp` values, there would still be a 10 minute window where the JWT would be considered valid by this library; 5 minutes one way for `nbf` and 5 minutes the other way for `exp`.

There is nothing against making the window smaller or even configurable so if you have a proposal, please voice it.

**Comment by javiesses** [comment]
Thank for your quick response!

I imagined that is was related to different clocks alignment, but don't you think it is too much to have a 10 minutes window? I think that window makes sense when the JWT has a long validity (measured in a unit greater than `hours`). If the use case is for authentication or something similar, where the token has a short validity (maybe minutes), then the service that integrates this package has the responsibility of implement an extra validation to check the times.

Maybe a good approach could be to do not use skewed times by default, just add an extra field to the `JWTVerifyOptions` type and use it if present. What do you think? 
I can submit that PR if necessary.

Thanks!

**Comment by javiesses** [comment]
Hi @mirceanis,
 
> Maybe a good approach could be to do not use skewed times by default, just add an extra field to the `JWTVerifyOptions` type and use it if present. What do you think?
> I can submit that PR if necessary.

What do you think about the proposal?

**Comment by mirceanis** [comment]
@javiesses, sorry for the late reply.
Yes, that sounds like a great idea!

This will be a breaking change since existing users of did-jwt might already be relying on this skew and not realizing it.

**Comment by javiesses** [comment]
Yep, it sounds like a breaking change, but we can bypass it, it depends on the approach we use.

I think there are two approaches:

1. Use a boolean flag that indicates if the comparison should be made against a skewed time or not. If `true`, will use the existing skew value: https://github.com/decentralized-identity/did-jwt/blob/c91d38cdd06635b418250048e329c509eab1e6d6/src/JWT.ts#L88
With this approach, the default value of that flag may be `true`, in that case, the change will not become a breaking one because the existing implementations will remain the same.

2. Use a numeric field indicating the skew value. By default it will not exist, so it will compare against the current time. This approach introduces a breaking change, but it is also more extensible because the developer choose the skew time.

IMHO, the first approach is simpler and it may be be released quicker because it doesn't introduce a breaking change.
It doesn't prevent us to use the other approach if necessary in the future as well

**Comment by mirceanis** [comment]
Since the second approach is more extensible, it makes sense to go for that one directly, but a gradual approach is also acceptable.
For the first option, instead of a boolean we could use the current (or smaller) default skew which could get overridden by the option in the `JWTVerifyOptions` if one is provided, and a future breaking change would set the default skew to 0.

The fact that it's a breaking change is not a blocker for a fast release; only it needs to be [marked as such in the commit message](https://github.com/semantic-release/semantic-release#commit-message-format).

If you want to contribute a PR for this, please make sure to add tests for the new corner cases that are created.
