### ISSUE TITLE
Comply with the did-resolution spec

### ISSUE THREAD

**Issue by oed** [decentralized-identity/did-jwt#144]
There is a did-resolution spec: https://w3c-ccg.github.io/did-resolution

Main thing this would involve is that there should be a new function, `dereference` which should return:
* DID Document
* DID Resolution Metadata
* DID Document Metadata

**Comment by mirceanis** [comment]
Right, thank you for raising this issue.
There is much work to be done to become conformant to that spec, even for the existing `resolve` method.

**Comment by oed** [comment]
I guess this will be solved by #150

**Comment by mirceanis** [comment]
right.. there's some cleanup that needs to happen to support that breaking change
