### ISSUE TITLE
Adapt to latest did-core-spec

### ISSUE THREAD

**Issue by mirceanis** [decentralized-identity/did-jwt#155]
This library is using some assumptions that no longer hold true against the latest did core spec.
More specifically, did resolution should now use:
* `DidResolutionResult` instead of `DIDDocument`
* `verificationMethod` instead of `publicKey` in the `DIDDocument`
* and `blockchainAccountId` instead of `ethereumAddress`

**Comment by OR13** [comment]
This is excellent, thanks for capturing these changes... regarding blockchainAccountId, this may be helpful:

https://github.com/OR13/lds-blockchain2021

https://or13.github.io/lds-blockchain2021/#did-document

**Comment by OR13** [comment]
Also keep an eye on https://github.com/w3c/did-spec-registries/issues/264

`blockchainAccountId` will stay, but probably the verification method types, like "EcdsaSecp256k1VerificationKey2019" will be removed from did core context in the future.

**Comment by mirceanis** [comment]
Thank you. I will try to keep up. Although, the spec keeps getting more and more convoluted every time I look again 😅
Fortunetely, this library doesn't do any JSON-LD processing for now.

**Comment by oed** [comment]
@OR13 What is `BlockchainVerificationMethod2021` supposed to mean? Seems like this could potentially include a lot of different things depending on a variety of different factors?

**Comment by OR13** [comment]
@oed its just something that uses `blockchainAccountId`... as far as I know, nobody was using `blockchainAccountId` yet.

**Comment by oed** [comment]
Ok, `blockchainAccountId` definitely makes a lot of sense. Was just wondering how one would interpret a `BlockchainSignature2021` for example :)
