### ISSUE TITLE
Rename x25519Encrypter, x25519Decrypter

### ISSUE THREAD

**Issue by awoie** [decentralized-identity/did-jwt#169]
The current naming convention is confusing and ambiguous. 

`x25519Encrypter` and `x25519Decrypter` actually refer to ECDH-ES+XC20PKW (X25519) with XChacha20Poly1305. They implement https://tools.ietf.org/html/draft-amringer-jose-chacha-02.

Technically, someone could also implement an encrypter for ECDH-ES+A256KW (X25519) with XChacha20Poly1305. The current naming convention would not allow us to distinguish between these two cases.

Let's discuss potential solutions to this problem. One solution could be ...

Renaming:
- `x25519Encrypter` -> `xc20pEncrypterEcdhEsX25519WithXc20Pkw`
- `x25519Decrypter` -> `xc20pDecrypterEcdhEsX25519WithXc20Pkw`

Schema is as follows:
`<ContentEncryptionAlg>Encrypter[(EcdhEs|Ecdh1Pu)<KeyAgreement>[With<KeyWrappingAlg>]]`

This would also match the currently implemented XC20P direct encrypter naming schema.

Future examples could be:
- `xc20pEncrypterEcdhEsX25519A256KW` which refers to ECDH-ES+A256KW (X25519) with XC20P content encryption
- `xc20pEncrpyterEcdhEsX25519` which refers to ECDH-ES (X25519) without KW

@oed @mirceanis what do you think?

**Comment by oed** [comment]
I think we need to change the structure of this repo. `x25519Encrypter` is a part of the xc20p module so saying that it is using xc20p would be kind of redundant.

**Comment by awoie** [comment]
> I think we need to change the structure of this repo. `x25519Encrypter` is a part of the xc20p module so saying that it is using xc20p would be kind of redundant.
> 
> However, we can change the names. I don't feel strongly :)

What would be redundant?

xc20p -> XChaCha20Poly1305, technically you could use a different curve than Curve25519 for key agreement. For example, P-256 would be also possible.

**Comment by oed** [comment]
Uh, I don't think this is stale.
