### ISSUE TITLE
`{ canonicalize: true }` stringifies the payload twice 

### ISSUE THREAD

**Issue by yhuard** [decentralized-identity/did-jwt#171]
Hi!

When using the new `{ canonicalize: true }` param in `createJWT`, the JWT generated looks incorrect. It produces something like: `IntcImFsZ1wiOlwiRVMyNTZLXCJ9Ig.IntcImFcIjpcImFcIixcInpcIjpcInpcIn0i.aKyOmGo5Dx2VsvDZAAHMxNtgqBeI0-qij4OB2AsISFdGsnNDJNEptZkQjY497mzX1LdMPS84pzykqalPtMwqMQ` (extracted from the tests). 

![image](https://user-images.githubusercontent.com/3524389/118781470-65a2ce00-b88d-11eb-9bdd-0baff4f71d82.png)

The issue is that the lib runs `JSON.stringify` on an already-stringified object: https://github.com/decentralized-identity/did-jwt/blob/4cfd3eef41d93cd0829b50c9a9bde9be3a0512d0/src/JWT.ts#L133 (`canonicalizeData` returns a string)

I can make a PR to remove the extra `JSON.stringify`. 

Thanks!

**Comment by mirceanis** [comment]
great catch!
yes, a PR is welcome.
