### ISSUE TITLE
TypeScript compiler errors when importing some file(s) if we use `"strict": true`  at tsconfig.json

### ISSUE THREAD

**Issue by Muhammad-Altabba** [decentralized-identity/did-jwt#174]
**The problem**
TypeScript compiler errors when importing some file(s) if we use `"strict": true`  at tsconfig.json.

**Details**
I have the following 
``` 
{
  "compilerOptions": {
     "strict": true,
....

```
When `import { toJose } from 'did-jwt/src/util';` the following error came:

```
node_modules/did-jwt/src/util.ts:75:18 - error TS2322: Type 'number | undefined' is not assignable to type 'number'.
  Type 'undefined' is not assignable to type 'number'.

75   return { r, s, recoveryParam }
                    ~~~~~~~~~~~~~

  node_modules/did-jwt/src/util.ts:67:70
    67 export function fromJose(signature: string): { r: string; s: string; recoveryParam: number } {
                                                                            ~~~~~~~~~~~~~
    The expected type comes from property 'recoveryParam' which is declared here on type '{ r: string; s: string; recoveryParam: number; }'
```

**Describe the solution you'd like**
I suggest to enable `strict` mode for the TypeScript compiler and fix for related issues. This will make the library more usable for other projects. 

**Describe alternatives you've considered**
I had to use `"strict": false` at my tsconfig.json which is something not desired.

**Comment by Muhammad-Altabba** [comment]
Do you like me to open an MR regarding this?

**Comment by mirceanis** [comment]
> Do you like me to open an MR regarding this?

Hey, thanks for reporting this.
There is already a PR( #175 ) with a fix for this issue and others, but it will take some more time until it is merged because of other potentially conflicting work that is in progress.

In the meantime, you can try to add `skipLibCheck: true` to your `tsconfig.json`

**Comment by Muhammad-Altabba** [comment]
Thanks @mirceanis ,
I add `skipLibCheck: true` to my `tsconfig.json`. This could make the plugin to compile. However, when using that plugin in another project I face the error: 

> netid-kms-plugin/node_modules/did-jwt/src/util.ts:1
> import * as u8a from 'uint8arrays'
> ^^^^^^
> SyntaxError: Cannot use import statement outside a module

This is because I could not import the function I need directly. I could only import it using:

`import { bytesToBase64url, hexToBytes, toJose } from 'did-jwt/src/util';
`

And that is because the functions inside did-jwt/src/util are not exported in the index file. I think we need to add the following to did-jwt/src/index.tx as follow:
```
export { 
  base58ToBytes, 
  base64ToBytes, 
  bytesToBase58, 
  bytesToBase64, 
  bytesToBase64url, 
  bytesToHex,
  decodeBase64url,
  encodeBase64url,
  fromJose,
  hexToBytes,
  EcdsaSignature,
  leftpad,
  parseKey,
  stringToBytes,
  toJose,
  toSealed} from './util'
```

What do you think?

Many thanks,

**Comment by mirceanis** [comment]
The required methods are small enough to be implemented directly in your code-base. If we export them from did-jwt then we would have to maintain them in future versions and at the moment they are out of the scope of this library.
After #170 is settled, then there might be a utility package, but until then it is easier to use something like `uint8arrays` directly to perform these encoding conversions.
