### ISSUE TITLE
did-jwt SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by ErvinDimitri** [decentralized-identity/did-jwt#176]
**Describe the bug**
I am getting the following bug:
SyntaxError: Unexpected token '.'

**To Reproduce**
I was trying to follow the example:
const didJWT = require('did-jwt')
const signer = didJWT.ES256KSigner('278a5de700e29faae8e40e366ec5012b5ec63d36ec77e8a2417154cc1d25383f')

**Screenshots**
![Screenshot (109)](https://user-images.githubusercontent.com/44121451/119151608-dabe0100-ba4f-11eb-8d07-1d29bdc3352a.png)

**Comment by mirceanis** [comment]
Which version of node are you using?

**Comment by ErvinDimitri** [comment]
> Which version of node are you using?

v12.14.1

**Comment by mirceanis** [comment]
Please try to run your app with node 14 and report if the error still shows

**Comment by ErvinDimitri** [comment]
> Please try to run your app with node 14 and report if the error still shows

I needed to update node, It's working now
Thanks for help

**Comment by CastilloLuis** [comment]
<img width="1680" alt="Screen Shot 2021-11-26 at 7 11 40 PM" src="https://user-images.githubusercontent.com/37077073/143660451-3776b306-b1b9-4884-b189-859853d3807d.png">
Hello, I'm having similar issue with node 14.17.0 @ErvinDimitri
