### ISSUE TITLE
`exports` field in `package.json` breaks CJS imports

### ISSUE THREAD

**Issue by PaulLeCam** [decentralized-identity/did-jwt#181]
**Describe the bug**
[This change](https://github.com/decentralized-identity/did-jwt/commit/029b429aa5fd9e1bc57ad6013c71a644f7b885ff#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R7) breaks CJS imports of the module:

```sh
[...]/did-jwt/lib/index.modern.js:1
import { toString, fromString, concat } from 'uint8arrays';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

**To Reproduce**
Try to import the module, for example `node -e "require('did-jwt')"`

**Expected behavior**
Module can be imported

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 10.14

**Additional context**
Using the `exports` field in `package.json` doesn't imply the file uses ESM, see https://nodejs.org/dist/latest-v16.x/docs/api/packages.html#packages_exports.

**Comment by mirceanis** [comment]
thank you for your vigilance. looking into it now

**Comment by mirceanis** [comment]
can you try again with version 5.5.2 ?

Please reopen if it still looks broken

**Comment by PaulLeCam** [comment]
Yes it works with 5.5.2, thanks!
