### ISSUE TITLE
add ability to use external `sharedSecret` function

### ISSUE THREAD

**Issue by mirceanis** [decentralized-identity/did-jwt#183]
### Context
When creating auth JWE or decrypting JWE, the current assumption is that there is access to secretKey material so that `sharedKey()` can be called directly.
Examples [here](https://github.com/decentralized-identity/did-jwt/blob/0db32116647bd69d265eafbee3094ffde1df937c/src/xc20pEncryption.ts#L275), [here](https://github.com/decentralized-identity/did-jwt/blob/0db32116647bd69d265eafbee3094ffde1df937c/src/xc20pEncryption.ts#L179) and [here](https://github.com/decentralized-identity/did-jwt/blob/0db32116647bd69d265eafbee3094ffde1df937c/src/xc20pEncryption.ts#L313)

### Problem
This prevents external crypto implementations from being used along with this library.

### Solution
In a similar fashion to the [`Signer`](https://github.com/decentralized-identity/did-jwt/blob/0db32116647bd69d265eafbee3094ffde1df937c/src/JWT.ts#L7) pattern, I'm proposing that a similar interface be used to allow the use of external crypto.

### Example:
```typescript
type ECDH = (theirPublicKey: Uint8Array) => Promise<Uint8Array>
```
with a possible implementation along the lines of:
```typescript
export function createX25519ECDH(mySecretKey: Uint8Array): ECDH {
  return async (theirPublicKey: Uint8Array): Promise<Uint8Array> => {
    return sharedKey(mySecretKey, theirPublicKey)
  }
}
```

**Comment by awoie** [comment]
That sounds good to me, also the naming makes sense.
