### ISSUE TITLE
JWTPayload "type" property

### ISSUE THREAD

**Issue by yhuard** [decentralized-identity/did-jwt#184]
Hi!

What is the `type` claim about?
https://github.com/decentralized-identity/did-jwt/blob/0db32116647bd69d265eafbee3094ffde1df937c/src/JWT.ts#L62
AFAIK, it's not a standard claim name (https://datatracker.ietf.org/doc/html/rfc7519#section-4.1), and it's causing issues with the repos I'm working on since https://github.com/decentralized-identity/did-jwt/commit/029b429aa5fd9e1bc57ad6013c71a644f7b885ff#diff-7cf1756e74ee58d67cca397cf6e4e522b18d04cbcd794affb6429aa912c547f3R235
Thanks!

Edit: by "issues", I mean the TypeScript compiler is now complaining because on our side we also have a `type` property on the object we want to pass to `createJWT`, and our `type` has a different type: `type?: string | string[];`

**Comment by mirceanis** [comment]
Good catch! and thanks for the _issues_ clarification.
You have spotted a bug, so `type` should indeed be defined as `type?: string | string[]`

You are welcome to provide a PR to fix [JWT.ts#L62](did-jwt/src/JWT.ts) if you are in a hurry.

**Comment by yhuard** [comment]
In my opinion, `type` should not be defined at all if it's not used by the library. And from what I've seen, it is indeed not used. It was added in https://github.com/decentralized-identity/did-jwt/commit/b9593dde27c378482937163174e7f0a0a6e585b0 as part of the "Convert to Typescript" (PR https://github.com/decentralized-identity/did-jwt/pull/36), but I couldn't find where it was used, so I guess it was just a mistake.
