### ISSUE TITLE
[BUG]  Support for the experimental syntax 'nullishCoalescingOperator' isn't currently enabled

### ISSUE THREAD

**Issue by dlsso** [decentralized-identity/did-jwt#210]
### Prerequisites

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Current Behavior

Using library in a project results in ` Support for the experimental syntax 'nullishCoalescingOperator' isn't currently enabled` when running `npm start`

### Expected Behavior

No error

### Failure Information

I am not using babel so I assume the config that the error says needs adjusting is in `did-jwt`.
Update: Looks like it might actually be `dids` that needs to adjust, but this project did break them by using nullish coalescing. Not sure whose responsibility that is. Looks like they could have prevented by locking to version `5.6.1`, but if nullish coalescing is actually a breaking change then it should have got a major version number, right?

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Use library
2. Try to `npm start`

#### Environment Details

Ubuntu on WSL2
Node v14.17.6
Npm v6.14.15

#### Failure Logs/Screenshots

```./node_modules/did-jwt/lib/index.module.js
SyntaxError: client/node_modules/did-jwt/lib/index.module.js: Support for the experimental syntax 'nullishCoalescingOperator' isn't currently enabled (1662:17):

  1660 |               // TODO: should be able to use non base58 keys too
  1661 |               return key.type === 'X25519KeyAgreementKey2019' && Boolean(key.publicKeyBase58);
> 1662 |             })) ?? [];
       |                 ^
  1663 |             if (!pks.length && !controllerEncrypters.length) throw new Error(`no_suitable_keys: Could not find x25519 key for ${did}`);
  1664 |             return pks.map(pk => x25519Encrypter(base58ToBytes(pk.publicKeyBase58), pk.id)).concat(...controllerEncrypters);
  1665 |           }

Add @babel/plugin-proposal-nullish-coalescing-operator (https://git.io/vb4Se) to the 'plugins' section of your Babel config to enable transformation.
```

#### Alternatives you considered

Please provide details about an environment where this bug does not occur. [N/A]

**Comment by mirceanis** [comment]
Thank you for reporting this.
Can you link to a project where this issue is manifesting?

**Comment by dlsso** [comment]
It was happening in this project: https://github.com/dlsso/blockchain-developer-bootcamp-final-project
I believe the way I got around it was by upgrading `react-scripts` to `5.0.0`.

The full project setup is a little complicated, but I expect you could replicate by cloning and
1. In client directory change `react-scripts` in `package.json` to `3.2.0` or any valid 3.x or 4.x version.
2. In client directory `yarn install` then `yarn start`

Note that I was forced to use an old-ish version of create react app, so that may have something to do with it. Also not sure if using ES2020 is considered a breaking change, so not sure if the issue is really even in this project or not. Didn't have time to dig in, unfortunately.

**Comment by mirceanis** [comment]
Thanks for the reply!

Since you found a workaround by using more recent tooling, and since that operator is supported by modern browsers and modern node, I'm going to close this without further changes.

Please reopen if you still encounter the problem.
