### ISSUE TITLE
[BUG] Module Loader fails on node v16.13.0

### ISSUE THREAD

**Issue by zoernert** [decentralized-identity/did-jwt#215]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

### Current Behavior

What is the current behavior?
`SyntaxError: Unexpected token '?'` when loading the module:

```javascript
 Request error! SyntaxError : Unexpected token '?'
./node_modules/did-jwt/lib/index.cjs:1690
 })) ?? [];
```

### Expected Behavior

No error when loading the module :)

### Failure Information

It suddenly appeared and I had no issue why it popped up or which change (either on the system or on the module) caused it.

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

#### Environment Details

* node/browser version: 16.13
* OS Version: Tested on Ubuntu 18.x, 20.x 
* Device details:

**Comment by mirceanis** [comment]
Please provide a few more details about your issue.

Did it appear after updating to a new version of did-jwt?
Did you update anything else in your project when this error appeared?
Can you link to a project that shares your setup where this issue can be reproduced?

**Comment by zoernert** [comment]
The issue appeared suddenly. Without any obvious change. Strange is, that I do not have an issue with my personal development notebook and one of my CI servers works fine too. However, 3 others fail - while all 4 CI servers have in theory the same configuration and were running the same tests. 

It could be that it appeared after the upgrade to 5.12.3 [Commit](https://github.com/decentralized-identity/did-jwt/commit/cf0bfc32c64c8491aecd1e38eb7ac231b209f91b). 

What I try to do now is to isolate a did-jwt module test case as the actual error appears in a lentgthly call stack at the moment. 

My hope (with this issue) is that someone else stumbled over the same issue.

**Comment by mirceanis** [comment]
Something similar has been reported in #210 and #213
It seemed to have something to do with the project config rather than this library, but if you can isolate this as a reproducible bug, then it will be easier to fix.

**Comment by zoernert** [comment]
Agree!

Following [gist](https://gist.github.com/zoernert/580768a0247128bc07b9c704c04adfa4) is the minimum isolation and it works on all 5 systems (4 CIs + my notebook). And the testJWT - String is as it got called in my test cases.

During my walk to isolate the  issue I got once a similar error from another module - which looks again strange and seems like a general issue somewhere in the call stack:
```
/node_modules/ethr-did-resolver/lib/index.js:1087
   blockTag = qParams.get('versionId') ?? blockTag;
                                                              ^
 SyntaxError: Unexpected token '?'
```

**Comment by zoernert** [comment]
Fun fact: 
If I move the `require` in my original code outside of the module scope (which is a bad idea here, as it is a microservice environment...) it works on all 5 systems.

**Comment by nick-verida** [comment]
We've been seeing a similar issue using `did-jwt`. We were originally having it under node 14 but have tried upgrading to node 16 and are still seeing the same issue. So far have been unable to solve it. Interestingly we are on Vue (not React, which is where other reports seem to have been). 

@zoernert I had a look at https://github.com/energychain/did-wallet-service/commit/e6e74e70f74119f693740eb80fea0512aacbdb6f but couldn't quite work out what you did to solve it. Any hints are appreciated!

**Comment by nick-verida** [comment]
I managed to fix this using the change suggested here: https://github.com/OnurGvnc/acorn-with-stage3

ie, adding this to package.json (we use yarn):

```
  "resolutions": {
    "acorn": "npm:acorn-with-stage3"
  },
  "dependencies": {
```

NPM users may want to look at https://github.com/webpack/webpack/issues/10227#issuecomment-698662228

**Comment by zoernert** [comment]
I think it is a part of the root cause. And maybe an issue with the memory management of Node itself.
