### ISSUE TITLE
question about data in signer

### ISSUE THREAD

**Issue by bshambaugh** [decentralized-identity/did-jwt#229]
How is data fed to the signer? This is a weird pattern.
https://github.com/decentralized-identity/did-jwt/blob/master/src/signers/ES256KSigner.ts#L31

**Comment by mirceanis** [comment]
If the data is a string, then it's converted to the byte array representation, otherwise the data is expected to be a byte array, in which case it is sent directly to the signer. The string conversion exists for convenience.

What would make it less weird? Your question is a bit vague; please help me understand.

**Comment by bshambaugh** [comment]
Somehow the signer grabs the payload and puts in the variable data and returns a signature. I collected all the component code in a gist from the did-jwt library that seems to work together:

https://gist.github.com/bshambaugh/2d37d55b71910a3a4c7dfcc03e41bf33

**Comment by mirceanis** [comment]
I think I understand your confusion now.
This is a common pattern in Javascript, where a function returns another function (as opposed to returning the result of another function).

In this case, the function `ES256KSigner` receives a private key parameter, and returns another function that receives a `data` parameter and signs it using the private key.

I suppose in C this would be returning a function pointer.. My C is very rusty so don't take my word for it.

To learn more about this pattern, I guess a good starting point is to search for documentation about Javascript closures.

I'm closing this issue, since it doesn't relate strictly to this library, but to a general Javascript pattern.
Feel free to reopen if I misunderstood.

**Comment by bshambaugh** [comment]
This is unrelated to this library. Apologies in advance.

rambling. ( I have been flailing about trying to think about my typescript problem and I am unsure who to ask to clear stuff up for me ....I feel that maybe I exhausted the local dev slack. ... locally I don't even think there is someone I could ask to pair-program with me at a coffee shop even for money. I've alluded to this when talking to people...and the community has known I've been working on this for months..but I haven't had much success...there is a newbie coding group I could try out tomorrow that meets every couple weeks or so..... I'll report back in a few hours....maybe I'll finally get lucky)

I put together some non-functional code
https://codesandbox.io/s/infallible-christian-y860j3?file=/index.js:387-1245

Here is the most interesting excerpt

```
async function getSignature(data) {  ... I suspect an async function with an eventEmitter is illegal....perhaps the same if it was replaced with a stream
   eventEmitter.emit('requestforsignature',data); // this emulates sending data over websockets to a remote device
   
   eventEmitter.on('requestforsignature', (chunk) => { // this emulates the remote device receiving the data and doing an operation on it
    const sig = bytesToBase64url(callToHSM(chunk));
    eventEmitter.emit('signature',sig);
   })

   eventEmitter.on('signature', (chunk) => {  // this is the response that the original sender recieves from the device...
     // console.log('signeddata:',chunk); 
     return chunk; // somehow the code returns the response when it gets it   .... I suspect this line is illegal
   });

}

/// this is the functionality I need, but it is not going to work
export function P256Signer(): Signer {
    return async(data: string | Uint8Array) : Promise<string> => {
       return getSignature(data);   ... I suspect this is illegal because return chunk is illegal
    }
}
```

**Comment by bshambaugh** [comment]
Errata. I apologize, the internet is intermittent here. If I succeed pushing these packets to the web, it should read:

```
 eventEmitter.once('signature', (chunk) => {  // this is the response that the original sender recieves from the device...
     // console.log('signeddata:',chunk); 
     return chunk; // somehow the code returns the response when it gets it   .... I suspect this line is illegal
   });
   ```

**Comment by bshambaugh** [comment]
I just found out from https://nodejs.org/api/stream.html that async/await was integrated with streams. Of course I can use once to trigger a Promise (https://www.derpturkey.com/event-emitter-to-promise/) on eventEmitter.once. I can also write stream.once on a duplex stream for incoming data.

**Comment by bshambaugh** [comment]
Looking at the previous, the pseudocode I've settled on is :

```
async function getSignature(payload) {
      let data = '2'+'1200'+payload; 
      stream.write(data);
  return new Promise((resolve,reject) => {
        stream.once('data',(resolve) => {
             return resolve;
        });
        stream.once('error',reject);
}

export function P256Signer(): Signer {    // signer like ed25519, secp256k1 signer in did-jwt
      return async(payload: string | Uint8Array): Promise<string> => {
            return await getSignature(payload);
      }
}

// so if you wanted the signature every 2 seconds....this code....but actually I want the signer to emulate this with a private key 
available on the network [](https://github.com/ceramicnetwork/key-did-provider-ed25519/blob/main/src/index.ts#L46-L56)
websocketServer.on('stream',function(stream,request) {
      setInterval(function(){ 
          getSignature(payload); // this may not be right....
      },2000);

})

**Comment by bshambaugh** [comment]
I will make a “cartoon” of animated video to illustrate the conceptualization I am trying to convey

**Comment by bshambaugh** [comment]
Okay here is the cartoon.

I seem to be stuck trying to embed a websocket connection within an async function. It could be that I am almost there. I made a video:

http://www.youtube.com/watch?v=ZrS4QRsLn98&t=4m15s

**Comment by bshambaugh** [comment]
fwiw, I did a weird hack as a result of making this video. It opened up my eyes so to speak. The previous video is not as relevant anymore.

https://github.com/bshambaugh/BlinkyProject/blob/remoteSigner/testJWTremoteSigner/src/P256Provider_class.ts

I'll try to find someone to pair program with on this.
