### ISSUE TITLE
EdDSASigner- The privatekeyBytes is 64?

### ISSUE THREAD

**Issue by yanyanxiaoyu** [decentralized-identity/did-jwt#238]
Hello,

I generated a private key by ED25519, and the private key is 32 bytes.
I want to use EdDSASigner to sign it, but it seems like the EdDSASigner will check the private key bytes. 
From my understanding, the ED25519 private key should be 32 bytes, right? I'm not sure if it is a bug or my misunderstanding. 
Expecting your reply!

Thanks.

**Comment by mirceanis** [comment]
how did you generate the private key?

This library [currently] uses `@stablelib/ed25519`, which uses the same conventions as [libsodium](https://github.com/jedisct1/libsodium) and [NaCl](http://nacl.cr.yp.to/) to represent key material.

In this convention, Ed25519 secret keys are represented on 64 bytes which I believe is actually the full keypair, not just the secret part, adding up to a total of 64 bytes.

I think after we manage to modularize this library (see #170) the EdDSASigner will likely lose that 64 byte check logic, or be replaced entirely by something new, depending on the underlying crypto package being used.

**Comment by yanyanxiaoyu** [comment]
> In this convention, Ed25519 secret keys are represented on 64 bytes which I believe is actually the **full keypair**, not just the secret part, adding up to a total of 64 bytes.

about the full keypair, does that means "privatekey+publickey" or "publickey + privatekey"?

**Comment by yanyanxiaoyu** [comment]
Hello,

Any question is that: 
when I call verifyEd25519, I got the error "Error: invalid_signature: Signature invalid for JWT", it seems like this error from the function verify(publicKey, message, signature). 

Do you have any idea about it?

Thanks.

**Comment by mirceanis** [comment]
> about the full keypair, does that means "privatekey+publickey" or "publickey + privatekey"?

It seems to be private+public. See [the code](https://github.com/StableLib/stablelib/blob/2f3b21e8fcee4aaa77872282fd4ac7a7ff1633f5/packages/ed25519/ed25519.ts#L670)

> when I call verifyEd25519, I got the error "Error: invalid_signature: Signature invalid for JWT", it seems like this error from the function verify(publicKey, message, signature).

I have no idea without more details. What parameters are you sending to the function?

**Comment by yanyanxiaoyu** [comment]
> 

Hi, I think I have found the issue, it is all caused by my misuse of the full keypair. Really thanks a lot.

**Comment by mirceanis** [comment]
I'm happy to hear that you solved it. I'm closing this then.
