### ISSUE TITLE
[proposal] Add support for SIOPv2 ID1 + JWT VC Presentation Profile

### ISSUE THREAD

**Issue by siacomuzzi** [decentralized-identity/did-jwt#250]
Accoarding to the [spec](https://identity.foundation/jwt-vc-presentation-profile/#id-token-validation), the `iss` claim must be `https://self-issued.me/v2/openid-vc` instead of `https://self-issued.me/v2`

Do you have plans to consider that in your `verifyJWT` method?

https://github.com/decentralized-identity/did-jwt/blob/86010a6f403619b85259b1790d9d21799716bd4b/src/JWT.ts#L407

**Comment by nklomp** [comment]
Please be aware that it is not instead of. The siopv2 spec lists the current value.

https://openid.net/specs/openid-connect-self-issued-v2-1_0-ID1.html#name-self-issued-id-token-valida

The jwt presentation interop profile adds the openid-vc value.

**Comment by nklomp** [comment]
Joy. The latest SIOPv2 spec has removed the self-issued.me value altogether.
The JWT VC Presentation Interop Profile is however based on Implementers Draft 1 of the SIOPv2 spec. The interop profile differs in value for the claim from the SIOPv2 ID1 specification. I asked for clarification in the interop profile Github: https://github.com/decentralized-identity/jwt-vc-presentation-profile/issues/63

**Comment by mirceanis** [comment]
Closed by #260
