### ISSUE TITLE
Key mapping function

### ISSUE THREAD

**Issue by sondreb** [decentralized-identity/did-jwt#263]
Not sure if this is a feature that fits in the `did-jwt` package or somewhere else, but `verifyJWS` takes a list of `VerificationMethod` and when it is used, a manual DID Document resolution need to be made.

In the resulting DID Document, the `assertionMethod` can be used to verify the jws signature, but the issue is that sometimes keys can be referencing keys held in the `verificationMethod` list, like '#key0'.

Would be nice to have a utility function that could take an DID Document and resolve all keys for different sections, not just an aggregate, but allowing the consumers of the function to tell which keys to get, e.g. `assertionMethod` or `authentication`.

**Comment by mirceanis** [comment]
This makes sense, and would definitely be useful, but it sounds more like a feature for the [did-resolver](https://github.com/decentralized-identity/did-resolver) library, don't you think?

Would you like to contribute an implementation?
