### ISSUE TITLE
Documentation not updated

### ISSUE THREAD

**Issue by user163** [decentralized-identity/did-jwt#287]
The documentation should be adapted to the current state of development, e.g. for version 7.2.2 according to the documentation [ES256KSigner][1]: _The supported encodings for the private key are hex, base64, base64url, and base58btc._ 

However, according to [code][2] only `Uint8Array` is allowed: `function ES256KSigner(privateKey: Uint8Array, recoverable = false)`.

Note: Before version 6.0.0 it was indeed possible to pass the key in various binary-to-text encodings.

[1]: https://github.com/decentralized-identity/did-jwt/blob/7.2.2/docs/guides/index.md#es256ksigner
[2]: https://github.com/decentralized-identity/did-jwt/blob/7.2.2/src/signers/ES256KSigner.ts

**Comment by mirceanis** [comment]
Thank you for reporting this!
Are you planning to open a PR with the fix?
