### ISSUE TITLE
[BUG] EdDSA signer accepts a 64 bytes `Uint8Array` while EdDSA private key is 32 Bytes

### ISSUE THREAD

**Issue by coodos** [decentralized-identity/did-jwt#289]
### Current Behavior

Currently if I go and try to create an EdDSA signer it expects a 64 Byte private key, while EdDSA private key is 32 bytes, I understand it wants to get a concatenated version of Private + Public, however in that case the variable naming seems misleading.

### Expected Behavior

It asks for a 32 Byte key, or the name is more suggestive that you require a concatenated key with priv+public

### Failure Information

Error: bad_key: Invalid private key format. Expecting 64 bytes, but got 32

#### Steps to Reproduce

1. Use a private key seed which is 32 bytes
2. try to create a EdDSA signer
3. observe the signer fail

#### Environment Details

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* node/browser version: v20.2.0
* OS Version: MacOS 13.0.1
* Device: MacBook Pro 2021 M1 Max

#### Alternatives you considered

I would be more than happy to add a pull request which makes it so that we can accept both 32 byte and 64, this way the current functionality doesn't break.

**Comment by mirceanis** [comment]
Not stale, this is still a bug.
@coodos we'd gladly accept a PR fixing this issue.
