### ISSUE TITLE
[BUG][deps] the update of uint8arrays>3.x and multiformats>9.x caused broken builds in CommonJS projects

### ISSUE THREAD

**Issue by mirceanis** [decentralized-identity/did-jwt#301]
As explained by @nklomp  in https://github.com/decentralized-identity/did-jwt-vc/issues/135, a dependency update was made that cascaded into broken builds.

This library is still being built as both CJS and ESM, but these 2 dependencies stopped publishing CJS variants in recent versions.
Unfortunately the maintainers of the above libraries don't want to publish CJS variants of their libraries so one of the few options remaining is to downgrade those dependencies here to ameliorate the annoyance for users of this library.

The JS world seems to be moving toward ESM but it is painfully slow and annoyingly difficult to support both.
I'm posting this issue here to gauge the support for the downgrade.

👍 downgrade   /  👎 do nothing ?

**Comment by nklomp** [comment]
Double negatives :P Downgrade is thumbsup right? ;)

IMO given the amount of issues people face right now, a downgrade makes sense, until you move the lib itself to full ESM.

**Comment by mirceanis** [comment]
> Double negatives :P Downgrade is thumbsup right? ;)

Good point, I edited my comment to be more clear about the meaning of the emojis :)
