### ISSUE TITLE
Please update @scure/base package

### ISSUE THREAD

**Issue by Kolezhniuk** [decentralized-identity/did-jwt#309]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

Hi! Could you please update `@scure/base` package dependency to remove next warning when I'm trying to build 
`did-jwt` package with rollup.
Please see https://github.com/paulmillr/scure-base/issues/31

```(!) node_modules/@scure/base/lib/esm/index.js (350:33): A comment

"/* @__PURE__ */"

in "node_modules/@scure/base/lib/esm/index.js" contains an annotation that Rollup cannot interpret due to the position of the comment. The comment will be removed to avoid issues.
https://rollupjs.org/https://rollupjs.org/configuration-options/#pure
```

Thanks

**Comment by mirceanis** [comment]
There doesn't seem to be a release of @scure/base with that fix yet.
We'll update when it gets released.
