### ISSUE TITLE
Multiple audiences in JWT?

### ISSUE THREAD

**Issue by hsnhrn** [decentralized-identity/did-jwt#54]
Describe the bug

If we put e.g. an array of audience during 

> createJWT()

 and verifiy it with an array of audience or just one audience it gives a matcherror. Let's say a DID document has audience 0x1 and 0x2 and now If i verify a JWT with audience 0x2. The verifyJWT function will gives

> TypeError: mnidOrDid.match is not a function

Is multiple audiences are allowed?

Expected behavior
It should verify with one of the audience defined during creation of JWT.

**Comment by mirceanis** [comment]
This is a bug.
The behavior you expected should be the correct one.
Thanks for reporting.
