### ISSUE TITLE
Expose JWS with support for detached payload

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/did-jwt#81]
**Is your feature request related to a problem? Please describe.**

Not possible to use this library to construct a Linked Data Proof Signature suite in the expected way.

**Describe the solution you'd like**

Support a createDetachedJws method that can yield a JWS with the following header:

For example: https://github.com/decentralized-identity/lds-ecdsa-secp256k1-2019.js/blob/master/packages/es256k-jws-ts/src/JWS.ts#L34

```
const header = {
  alg: "ES256K-R",
  b64: false,
  crit: ["b64"],
};
```
**Describe alternatives you've considered**
https://github.com/decentralized-identity/lds-ecdsa-secp256k1-2019.js (ES256K)

**Additional context**
In order to support ES256K-R, in the existing tooling ecosystem, we should construct a suite that supports both JWT and Linked Data Proof Variants, as is the case with:

https://github.com/w3c-ccg/lds-jws2020

However, since ES256K-R is not standard (or in an IETF draft) we cannot use any off the shelf libraries to implement support for it... IMO this repo would be the best place to standardize an implementation of this.

**Comment by oed** [comment]
I believe this should be possible to do now with the addition of the `createJWS` and `verifyJWS` functions.

**Comment by OR13** [comment]
Would be nice to show that the implementation of ES256K-R here: https://github.com/decentralized-identity/EcdsaSecp256k1RecoverySignature2020

works with these new functions.
