### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by gemcutterjp** [decentralized-identity/did-jwt#91]
**Describe the bug**
didJWT.verifyJWT does not return an object, and throws an error.

**To Reproduce**
1. Run the below code
````
 const providerConfig = {name:'ropsten',rpcUrl: `https://ropsten.infura.io/ws/v3/${process.env.INFURA_PROJECT_ID}`}
 const ethrDidResolver = getResolver(providerConfig)
 const resolver = new Resolver(ethrDidResolver)
 
 didJWT.verifyJWT(jwt,{
         resolver,
         audience: did
 }).then((response)=>{
         verifiedResponse=response,
 }).catch ((err) =>{
         console.log(err)
 })
````
2. See error
(node:93691) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at /Users/gemcutter/server/node_modules/ethjs-query/lib/index.js:108:99
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:93691) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:93691) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Expected behavior**
Returns an object resembling like below.
````
{
  payload: {
    iat: 1571692448,
    exp: 1957463421,
    aud: 'did:ethr:0xf3beac30c498d9e26865f34fcaa57dbb935b0d74',
    name: 'uPort Developer',
    iss: 'did:ethr:0xf3beac30c498d9e26865f34fcaa57dbb935b0d74'
  },
  doc: {
    '@context': 'https://w3id.org/did/v1',
    id: 'did:ethr:0xf3beac30c498d9e26865f34fcaa57dbb935b0d74',
    publicKey: [ [Object] ],
    authentication: [ [Object] ]
  },
  issuer: 'did:ethr:0xf3beac30c498d9e26865f34fcaa57dbb935b0d74',
  signer: {
    id: 'did:ethr:0xf3beac30c498d9e26865f34fcaa57dbb935b0d74#owner',
    type: 'Secp256k1VerificationKey2018',
    owner: 'did:ethr:0xf3beac30c498d9e26865f34fcaa57dbb935b0d74',
    ethereumAddress: '0xf3beac30c498d9e26865f34fcaa57dbb935b0d74'
  },
  jwt: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NkstUiJ9.eyJpYXQiOjE1NzE2OTI0NDgsImV4cCI6MTk1NzQ2MzQyMSwiYXVkIjoiZGlkOmV0aHI6MHhmM2JlYWMzMGM0OThkOWUyNjg2NWYzNGZjYWE1N2RiYjkzNWIwZDc0IiwibmFtZSI6InVQb3J0IERldmVsb3BlciIsImlzcyI6ImRpZDpldGhyOjB4ZjNiZWFjMzBjNDk4ZDllMjY4NjVmMzRmY2FhNTdkYmI5MzViMGQ3NCJ9.xd_CSWukS6rK8y7GVvyH_c5yRsDXojM6BuKaf1ZMg0fsgpSBioS7jBfyk4ZZvS0iuFu4u4_771_PNWvmsvaZQQE'
}
````
**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.4
 - Browser: chome
 - Version: 81.0.4044.129

**Additional context**
Before running the above code, the both of the below codes went through successfully.
didJWT.createJWT({aud:did,exp:1957463421,name:'pcp'},{alg:'ES256K-R',issuer:did,signer})
didJWT.decodeJWT(jwt)

**Comment by oed** [comment]
Thanks for reporting @gemcutterjp! Can you please provide the JWT that is causing this issue? Would help with debugging.

**Comment by gemcutterjp** [comment]
Thank you for your response.
Here is the JWT.

eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NkstUiJ9.eyJpYXQiOjE1ODg5MjIwMDYsImV4cCI6MTk1NzQ2MzQyMSwiYXVkIjoiZGlkOmV0aHI6MHg4ZjU3MjVjZWE1OGNhNjUzMjZiYTlhZWFlMGMwYzZkYmQ1YTY0NWZlIiwibmFtZSI6InBjcCIsImlzcyI6ImRpZDpldGhyOjB4OGY1NzI1Y2VhNThjYTY1MzI2YmE5YWVhZTBjMGM2ZGJkNWE2NDVmZSJ9.Kl4hvElC2rLYWHV9Fkgx1sQPYSLrY5o5QjKt09en15LdWpdz5ON_qj8NJskSQUuAa_lOlZBwVLZ3vAU4l3xPrAA

**Comment by mirceanis** [comment]
@gemcutterjp Please use the proper infura URL:

```typescript
 const providerConfig = {
  name:'ropsten',
  rpcUrl: `https://ropsten.infura.io/v3/${process.env.INFURA_PROJECT_ID}`
}
 const ethrDidResolver = getResolver(providerConfig)
 const resolver = new Resolver(ethrDidResolver)
 
 didJWT.verifyJWT(jwt,{
         resolver,
         audience: did
 }).then((response)=>{
         verifiedResponse=response,
 }).catch ((err) =>{
         console.log(err)
 })
```

The URL you are using has an extra `/ws` in the path.

If this fixes it for you, please close the issue.

**Comment by gemcutterjp** [comment]
Removing `/ws` fixed the issue.  I needed to pay an extra care to the rpcUrl.
I close the issue on this.
Having said that, I might suggest that throwing a more user-friendly error message should help.
